# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/DateTimeX-Auto/project>
	:perl_version_from
		_:main;
	:version_from
		_:main;
	:readme_from
		_:main;
	:test_requires
		"Test::More 0.61";
	:requires 
		"Carp 0",
		"DateTime 0",
		"DateTime::Format::Strptime 0",
		"UNIVERSAL::ref 0",
		"Object::AUTHORITY 0".

_:main <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/DateTimeX/Auto.pm" .

